version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: travel-app-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/travelapp
      - JWT_SECRET=my_password_very_very
      - NODE_ENV=development
      - BACKEND_PORT=5005
    ports:
      - "5005:5005"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules # Zapewnia poprawne działanie zależności

  frontend:
    build:
      context: ./frontend
    container_name: travel-app-frontend
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Zapewnia poprawne działanie zależności
    command: npm run dev # Uruchamia serwer deweloperski Vite

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
